name 'synyx-mongodb'
version '0.1.0'
author 'Johannes Graf'
license 'MIT License'
project_page 'https://github.com/synyx/puppet-mongodb'
source 'https://github.com/synyx/puppet-mongodb.git'
summary 'Puppet module to install and manage mongodb from 10gen repo'
description 'A Puppet module to install and manage mongodb from 10gen repo'
dependency 'puppetlabs/stdlib', '3.x'
dependency 'puppetlabs/apt', '1.x'
